# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

matrix:
  include:
  - r: release
    sudo: true
    cache: packages
    before_install:
      - cd InSilicoVA
      - jdk_switcher use oraclejdk8
    script:
      - R CMD javareconf
      - R CMD build --no-build-vignettes --no-manual . 
      - R CMD check --no-build-vignettes --no-manual --timings *tar.gz
  - r: release
    sudo: true
    cache: packages
    before_install:
      - cd InSilicoVA
      - jdk_switcher use oraclejdk9
    script:
      - R CMD javareconf -e
      - R CMD build --no-build-vignettes --no-manual . 
      - R CMD check --no-build-vignettes --no-manual --timings *tar.gz

# do not build vignettes...takes too long and times out on travis
#r_build_args: --no-build-vignettes --no-manual
#r_check_args: --no-build-vignettes --no-manual --timings

  