# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

matrix:
  include:
  - r: release
    addons:
      apt:
        packages:
	  - openjdk-7-jdk
    jdk: openjdk7
    sudo: false
    cache: packages
    before_install:
      - cd InSilicoVA
    script:
      - R CMD javareconf -e
      - R CMD build --no-build-vignettes --no-manual . 
      - R CMD check --no-build-vignettes --no-manual --timings *tar.gz
  - r: release
    addons:
      apt:
        packages:
	  - openjdk-8-jdk
    jdk: openjdk7
    sudo: false
    cache: packages
    before_install:
      - cd InSilicoVA
    script:
      - R CMD javareconf -e
      - R CMD build --no-build-vignettes --no-manual . 
      - R CMD check --no-build-vignettes --no-manual --timings *tar.gz
  # - r: release
  #   jdk: oraclejdk8
  #   sudo: false
  #   cache: packages
  #   before_install:
  #     - cd InSilicoVA
  #   script:
  #     - R CMD javareconf -e
  #     - R CMD build --no-build-vignettes --no-manual . 
  #     - R CMD check --no-build-vignettes --no-manual --timings *tar.gz
  # - r: release
  #   jdk: oraclejdk9
  #   sudo: false
  #   cache: packages
  #   before_install:
  #     - cd InSilicoVA
  #   script:
  #     - R CMD javareconf -e
  #     - R CMD build --no-build-vignettes --no-manual . 
  #     - R CMD check --no-build-vignettes --no-manual --timings *tar.gz
  # - r: release
  #   jdk: oraclejdk11
  #   sudo: false
  #   cache: packages
  #   before_install:
  #     - cd InSilicoVA
  #   script:
  #     - R CMD javareconf -e
  #     - R CMD build --no-build-vignettes --no-manual . 
  #     - R CMD check --no-build-vignettes --no-manual --timings *tar.gz

# do not build vignettes...takes too long and times out on travis
#r_build_args: --no-build-vignettes --no-manual
#r_check_args: --no-build-vignettes --no-manual --timings

  