# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

matrix:
  include:
  - r: release
    sudo: true
    cache: packages
    before_install:
      - cd InSilicoVA
      - sudo apt install -y openjdk-8-jdk
      - sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    script:
      - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
      - export PATH=$JAVA_HOME/bin:$PATH
      - R CMD javareconf -e
      - R CMD build --no-build-vignettes --no-manual . 
      - R CMD check --no-build-vignettes --no-manual --timings *tar.gz
  - r: release
    sudo: true
    cache: packages
    before_install:
      - cd InSilicoVA
    script:
      - R CMD javareconf
      - R CMD build --no-build-vignettes --no-manual . 
      - R CMD check --no-build-vignettes --no-manual --timings *tar.gz

# do not build vignettes...takes too long and times out on travis
#r_build_args: --no-build-vignettes --no-manual
#r_check_args: --no-build-vignettes --no-manual --timings

  
