# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

matrix:
  include:
  - r: release
    sudo: true
    cache: packages
    before_install:
      - cd InSilicoVA
      - sudo apt install -y openjdk-8-jdk
      - sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    script:
      - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
      - export PATH=$JAVA_HOME/bin:$PATH
      - R CMD javareconf
      - R CMD build --no-build-vignettes --no-manual . 
      - R CMD check --no-build-vignettes --no-manual --timings *tar.gz
  - r: release
    sudo: true
    cache: packages
    before_install:
      - curl -o openjdk-9.0.4_linux-x64_bin.tar.gz https://download.java.net/java/GA/jdk9/9.0.4/binaries/openjdk-9.0.4_linux-x64_bin.tar.gz
      - sudo mkdir /usr/local/java; sudo mv openjdk-9.0.4_linux-x64_bin.tar.gz /usr/local/java/
      - cd /usr/local/java; sudo tar xvfz openjdk-9.0.4_linux-x64_bin.tar.gz
      - cd; cd InSilicoVA
    script:
      - export JAVA_HOME=/usr/local/java/jdk-9.0.4
      - export PATH=$JAVA_HOME/bin:$PATH
      - R CMD javareconf
      - R CMD build --no-build-vignettes --no-manual . 
      - R CMD check --no-build-vignettes --no-manual --timings *tar.gz
  - r: release
    sudo: true
    cache: packages
    before_install:
      - curl -o openjdk-10.0.2_linux-x64_bin.tar.gz https://download.java.net/java/GA/jdk10/10.0.2/19aef61b38124481863b1413dce1855f/13/openjdk-10.0.2_linux-x64_bin.tar.gz
      - sudo mkdir /usr/local/java; sudo mv openjdk-10.0.2_linux-x64_bin.tar.gz /usr/local/java/
      - cd /usr/local/java; sudo tar xvfz openjdk-10.0.2_linux-x64_bin.tar.gz
      - cd; cd InSilicoVA
    script:
      - export JAVA_HOME=/usr/local/java/jdk-10.0.2
      - export PATH=$JAVA_HOME/bin:$PATH
      - R CMD javareconf
      - R CMD build --no-build-vignettes --no-manual . 
      - R CMD check --no-build-vignettes --no-manual --timings *tar.gz
  - r: release
    sudo: true
    cache: packages
    before_install:
      - cd InSilicoVA
    script:
      - R CMD javareconf
      - R CMD build --no-build-vignettes --no-manual . 
      - R CMD check --no-build-vignettes --no-manual --timings *tar.gz

# do not build vignettes...takes too long and times out on travis
#r_build_args: --no-build-vignettes --no-manual
#r_check_args: --no-build-vignettes --no-manual --timings

  
