# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

sudo: false
cache: packages
before_install:
 - cd InSilicoVA

# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

jobs:
  include:
  - language: java
    jdk: oraclejdk7
  include:
  - language: java
    jdk: oraclejdk8
  include:
  - language: java
    jdk: oraclejdk9
  include:
  - language: java
    jdk: oraclejdk10
  include:
  - language: java
    jdk: oraclejdk11
    
